#!/usr/bin/env bash

if ! test -e custom.css; then
   cp custom.css.template custom.css
   echo "Wrote custom.css"
fi

if ! test -e index.html; then
   cp index.html.template index.html
   echo "Wrote index.html"
fi

if ! test -e img; then
   mkdir img
   echo "Created empty directory img/"
fi
